--- #YAML:1.0
name:                PDF-Reuse-Barcode
version:             0.06
abstract:            ~
license:             ~
author:
    - Lars Lundberg larslund@cpan.org
generated_by:        ExtUtils::MakeMaker version 6.42_01
distribution_type:   module
requires:
    Barcode::Code128:              0
    GD::Barcode:                   0
    GD::Barcode::Code39:           0
    GD::Barcode::COOP2of5:         0
    GD::Barcode::EAN13:            0
    GD::Barcode::EAN8:             0
    GD::Barcode::IATA2of5:         0
    GD::Barcode::Industrial2of5:   0
    GD::Barcode::ITF:              0
    GD::Barcode::Matrix2of5:       0
    GD::Barcode::NW7:              0
    GD::Barcode::UPCA:             0
    GD::Barcode::UPCE:             0
    PDF::Reuse:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
